import "../styles/globals.css";
import Head from "next/head";
import { PetraWallet } from "petra-plugin-wallet-adapter";
import { AptosWalletAdapterProvider } from "@aptos-labs/wallet-adapter-react";
import Header from "../components/header";
import ThemeRegistry from "../theme/ThemeRegistry";
function MyApp({ Component, pageProps }) {
    const getwallets = [new PetraWallet()];
    return (
        <AptosWalletAdapterProvider plugins={getwallets} autoConnect={true}>
            <ThemeRegistry>
                <Head>
                    <title>Aptofy Radio</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Header />
                <div className="p-3 text-black">
                    <Component {...pageProps} />
                </div>
            </ThemeRegistry>
        </AptosWalletAdapterProvider>
    );
}

export default MyApp;
